<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>

    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <PlatformTarget>x64</PlatformTarget>
    <Platforms>x64</Platforms>

    <ApplicationIcon>Image\RoomTalk.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Image\RoomTalk.ico" />
    <Resource Include="Image\RoomTalk.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="NAudio" Version="2.3.0" />
  </ItemGroup>

</Project>